### ISSUE TITLE
not sure

### ISSUE THREAD

**Issue by RaNaMaster** [brainwave9/SiriProxy-XBMC#9]
im not sure whats going on i wasnt able to get the frodo to work so i when back to eden and  still no luck please look at this tv shows worked fine but  when i strat a movie it crashes

[Info - Plugin Manager] Processing 'Play Big Bang. '
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::Isy99i:0x8f7a604
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::XBMC:0x9288314
[Info - Plugin Manager] Matches (?i-mx:play (.+?)(?: in the (._))?$)
[Info - Plugin Manager] Applicable states: 
[Info - Plugin Manager] Current state: 
[Info - Plugin Manager] Matches, executing block
[SiriProxy-XBMC] Connecting to the XBMC interface (default)
[SiriProxy-XBMC] XBMC API Version 4 - Eden
[SiriProxy-XBMC] Finding TV show (API version 4)
[SiriProxy-XBMC] Looking up first unwatched episode (API version 4)
[Info - Plugin Manager] Say: Now playing "The Date Night Variable" (The Big Bang Theory, Season 6, Episode 1)
[SiriProxy-XBMC] Playing file (API version 4)
[Info - Plugin Manager] Sending Request Completed
[Info - iPhone] Received Object: Metrics
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: SpeechRecognized
[Info - Plugin Manager] Processing 'Play the avengers '
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::Isy99i:0x8f7a604
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::XBMC:0x9288314
[Info - Plugin Manager] Matches (?i-mx:play (.+?)(?: in the (._))?$)
[Info - Plugin Manager] Applicable states: 
[Info - Plugin Manager] Current state: 
[Info - Plugin Manager] Matches, executing block
[SiriProxy-XBMC] Connecting to the XBMC interface (default)
[SiriProxy-XBMC] XBMC API Version 4 - Eden
[SiriProxy-XBMC] Finding TV show (API version 4)
[SiriProxy-XBMC] Finding movie (API version 4)
/home/rana/.rvm/gems/ruby-1.9.3-p362@SiriProxy/bundler/gems/SiriProxy-XBMC-152bd5c4b6dd/lib/xbmc_library.rb:99:in `find_movie': undefined method`each' for nil:NilClass (NoMethodError)
    from /home/rana/.rvm/gems/ruby-1.9.3-p362@SiriProxy/bundler/gems/SiriProxy-XBMC-152bd5c4b6dd/lib/siriproxy-xbmc.rb:190:in `block in <class:XBMC>'
    from /home/rana/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/cora-0.0.4/lib/cora/plugin.rb:47:in`instance_exec'
    from /home/rana/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/cora-0.0.4/lib/cora/plugin.rb:47:in `block (2 levels) in process'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

**Comment by mgtiger** [comment]
I'm getting the same thing with Eden and Frodo

**Comment by RaNaMaster** [comment]
im still trying to make it work i have not had much luck but please let us know if you find a fix

**Comment by Deanmv** [comment]
The latest commits to this plugin work fine for me on both Eden and Frodo Beta 3. Try copying in the latest version of xvmc_library.rb (re-download it from github) into your plugin folder, even though you were running the latest commit (152bd5c4b6dd) there is no reason why it should work for me but not you unless something in that file is wrong.

**Comment by RaNaMaster** [comment]
thats a plugin for homeautomation Isy99i https://github.com/hoopty3/siriproxy-isy99i

Date: Sat, 19 Jan 2013 04:44:23 -0800

**Comment by Deanmv** [comment]
Yeah I realised after and changed my comment, apologies.

**Comment by mgtiger** [comment]
I figured it out. It was crashing because I didn't have any TV shows in my library. As soon as I added a (fake) TV show title, everything worked fine. So we have a workaround, but it would be nice if it didn't require TV shows.

**Comment by RaNaMaster** [comment]
thank you mgtiger that worked

**Comment by Deanmv** [comment]
Plugin could be changed to say something like "play movie" or "Play TV show" so it only scans one library which would stop this?

**Comment by Deanmv** [comment]
I've pushed an update to my forked version here: https://github.com/Deanmv/SiriProxy-XBMC/commit/ae97b2f540a4346c26864db0177cf61268ebfe26 Splits the TV and Movie commands seperate (now "play movie ..." or "play tv show...") Not tested a lot but think it works, if you could and it works then can submit a pull request.

**Comment by RaNaMaster** [comment]
its working good on my side thank you for the update also i have an idea the for the multiroom configuration how about a default room where i dont need to say the room name. and for all other rooms by name

**Comment by Deanmv** [comment]
I am only using one room configuration at the moment but do you mean that if you have more than one and say "play" then it will always ask you for a room?

As this can already be done:

This command can be used to test the plugin is working. Siri will respond with "XBMC is online" Optionally you can specify a room name if you have configured the plugin for multiple rooms.

`I'm in the <room name>
Use the <room name>
Control the <room name>`
These commands set the active room. All commands will be sent to this room, until you specify another room of course.
